name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  # - name: "Create env file"
  #   run: |
  #     touch .env
  #     cat .env

  # - name: Cache js dependencies
  #       id: cache-js
  #       uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: deps-${{ hashFiles('**/package-lock.json') }}

  #     - name: Cache php dependencies
  #       id: cache-php
  #       uses: actions/cache@v3
  #       with:
  #         path: vendor
  #         key: deps-${{ hashFiles('**/composer.lock') }}

  #     - name: Install js dependencies
  #       if: steps.cache-js.outputs.cache-hit != 'true'
  #       run: npm ci

  #     - name: Install php dependencies
  #       if: steps.cache-php.outputs.cache-hit != 'true'
  #       run: composer install

  # - name: Run tests
  #   run: npm test  # Add your test command here (if any)

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.3
        env:
          DOTENV_PRIVATE_KEY_PRODUCTION: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT || 22 }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true # Stop on error
          timeout: 10m
          envs: DOTENV_PRIVATE_KEY_PRODUCTION
          script: |
            ${{ vars.SERVER_SCRIPT }}
